name: Deploy Portfolio
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: 69.62.106.92
        username: root
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        script: |
          echo "Test connection"
          hostname